[package]
name = "gnostfinder"
version = "0.1.0"
edition = "2024"

[dependencies]

bevy = "0.16.1"
bevy_ratatui = { version = "0.9.2", features = ["windowed"] }
english = "0.1.3"
petgraph = "0.8.2"
ratatui = "0.29.0"

hashbrown = "0.16"
rustc-hash = "2.1"
